### ISSUE TITLE
joint_state_broadcaster publish wrong joint velocity

### ISSUE THREAD

**Issue by OTT123** [ros-controls/ros2_controllers#1230]
**Describe the bug**
I used joint_state_broadcaster to send the status of the robot in gazebo to topic /joint_states.

When I check the information in /joint_states, I found that the position was accurate, but the velocity was completely singular.

You can observe this phenomenon in the graph below. When the position is held still, the speed also remains at a constant value, and the trend of speed and position is exactly similar.

I wonder how joint_state_broadcaster gets the joint speed? How did this strange phenomenon come about?

**Screenshots**
![20240729-165559](https://github.com/user-attachments/assets/d25f4d51-ca9f-4267-9a5f-9842c712acb6)

**launch file**
```
controller_manager:
  ros__parameters:
    update_rate: 1000
    use_sim_time: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - some joints
    command_interfaces:
      - position
      # - velocity

    state_interfaces:
      - position
      - velocity
      # - effort
```
**Environment (please complete the following information):**
 - OS: ubuntu22.04
 - Version: ros humble, gazebo 11
