### ISSUE TITLE
Redeclaration of joint trajectory controller parameters

### ISSUE THREAD

**Issue by livanov93** [ros-controls/ros2_controllers#129]
While testing joint trajectory controller I have encountered an error regarding redeclaration of parameters. 
I think it is done twice, in[ controller interface](https://github.com/ros-controls/ros2_control/blob/ec8b0066685ce24ce28eaf439b0b353207bb6bb1/controller_interface/src/controller_interface.cpp#L27) (base class) and in [joint trajectory controller itself](https://github.com/ros-controls/ros2_controllers/blob/65874894b4f6db1b6075f642f2c5dab8d5c68882/joint_trajectory_controller/src/joint_trajectory_controller.cpp#L66).

The parameters were loaded via this file:
```
controller_manager:
  ros__parameters:
    update_rate: 100

    forward_command_controller_position:
      type: forward_command_controller/ForwardCommandController

    joint_state_controller:
      type: joint_state_controller/JointStateController

    ur_joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

ur_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.0
```
