### ISSUE TITLE
Joint-based ForwardCommandController

### ISSUE THREAD

**Issue by qleonardolp** [ros-controls/ros2_controllers#1523]
I've been working with generic command interfaces, using [ethercat_driver_ros2](https://github.com/ICube-Robotics/ethercat_driver_ros2), with many modules (+10), then my controller configuration file has various (at least four) controllers for each module/joint and their generic command interface using ForwardCommandController, such as:

```yaml
controller_manager:
  ros__parameters:
    joint_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_1_controlword:
      type: forward_command_controller/ForwardCommandController

    joint_1_opmode:
      type: forward_command_controller/ForwardCommandController

    joint_1_resetfault:
      type: forward_command_controller/ForwardCommandController

joint_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort
    joints:
      - joint_1

joint_1_controlword:
  ros__parameters:
    joints:
      - joint_1
    interface_name: control_word

joint_1_opmode:
  ros__parameters:
    joints:
      - joint_1
    interface_name: mode_of_operation

joint_1_resetfault:
  ros__parameters:
    joints:
      - joint_1
    interface_name: reset_fault
```

**Describe the solution you'd like**
For multiple joints, we can do the following:

```yaml
    controlword_controller:
      type: forward_command_controller/ForwardCommandController

controlword_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
    interface_name: control_word
```
However, it requires to known the respective position (index) of each joint when publishing on controlword_controller/commands (`std_msgs/msg/Float64MultiArray`). 

Would it be possible to work with `ForwardCommandController` in a similar way as `JointTrajectoryController` does, passing the joint name, i.e. `frame_id`?

Alternatively, would it be possible to work with `JointTrajectoryController` with command interface other than "position", "velocity", "acceleration", "effort"? Considering [joint_trajectory_controller_parameters.yaml](https://github.com/ros-controls/ros2_controllers/blob/master/joint_trajectory_controller/src/joint_trajectory_controller_parameters.yaml) file, I believe it is not, but I'm just checking it here.
