### ISSUE TITLE
robot not moving using velocity command interface only in joint_trajectory_controller

### ISSUE THREAD

**Issue by jintaoChan** [ros-controls/ros2_controllers#1631]
Hi guys,

**Here is some background information.**

1. moveit_config is generated by moveit setup assistant.
2. I modified some of the files in moveit_config(as below)
3. My robot driver accept only one kind of command interface be active at a same time. Meanwhile, the position command make the motor vibrate. So I have to use velocity only.

**Here is the problem**
hardware_interface got velocity command value which is 0.

**Here is the what had I tried to solve the problem**
Add position command & velocity command. The joint_trajectory_controller output correct value.

**This is my ros2_controllers.yaml**

```
# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    store_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

store_manipulator_controller:
  ros__parameters:
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
```

**This is my \*.ros2_control.xacro**

```
<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="TechJoints_ros2_control" params="name prefix eth_device">

    <ros2_control name="${name}" type="system">
      <hardware>
        <plugin>TechControlInterface/TechHardwareInterface</plugin>

        <param name="eth_device">${eth_device}</param>
      </hardware>

      <joint name="${prefix}joint2">
        <state_interface name="position"/>
        <command_interface name="velocity"/>
        <state_interface name="velocity"/>
      </joint>
      <joint name="${prefix}joint3">
        <state_interface name="position"/>
        <command_interface name="velocity"/>
        <state_interface name="velocity"/>
      </joint>
      <joint name="${prefix}joint4">
        <state_interface name="position"/>
        <command_interface name="velocity"/>
        <state_interface name="velocity"/>
      </joint>
        <joint name="${prefix}joint5">
        <state_interface name="position"/>
        <command_interface name="velocity"/>
        <state_interface name="velocity"/>
      </joint>
      <!-- <joint name="${prefix}joint6">
        <state_interface name="position"/>
        <command_interface name="velocity"/>
        <state_interface name="velocity"/>
      </joint> -->
    </ros2_control>

  </xacro:macro>

</robot>
```

**Comment by christophfroehlich** [comment]
Can you add the fix to your problem for other users in the future?

**Comment by jintaoChan** [comment]
> Can you add the fix to your problem for other users in the future?

I thought here is not a right place to ask a question.

**Comment by jintaoChan** [comment]
I fix this by adding a gain in ros2_controller.yaml(as below)

```
# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    store_manipulator_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

store_manipulator_controller:
  ros__parameters:
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    gains:
      joint2:
        p: 10.0
        i: 0.0
        d: 1.0
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      joint3:
        p: 10.0
        i: 0.0
        d: 1.0
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      joint4:
        p: 10.0
        i: 0.0
        d: 1.0
        i_clamp: 1.0
        ff_velocity_scale: 1.0
      joint5:
        p: 10.0
        i: 0.0
        d: 1.0
        i_clamp: 1.0
        ff_velocity_scale: 1.0

```
