### ISSUE TITLE
mecanum driver controller shows weird behaviour with reference_timeout

### ISSUE THREAD

**Issue by thedevmanek** [ros-controls/ros2_controllers#1683]
**Describe the bug**
I have a publisher constantly publishing to cmd_vel topic. The robot happily accepts the cmd till reference_timeout is reached.Once the robot hits timeout. It publishes nan to linear x,y and angular z. Which after reading the [code](https://github.com/ros-controls/ros2_controllers/blob/humble/mecanum_drive_controller/src/mecanum_drive_controller.cpp#L380C3-L396C4)
is expected.The problem is once the timeout is reached the robot does not take any further cmds
**To Reproduce**
1. Run the example code in https://github.com/ros-controls/gz_ros2_control/tree/humble/gz_ros2_control_demos

**Expected behavior**
The controller is supposed to pick up new cmds as they come and not permanently stop. 

**Screenshots**
https://github.com/user-attachments/assets/ed4e9d2a-482c-42cf-946f-bf42cc0ecd39
https://github.com/user-attachments/assets/aee966c0-1175-4b84-945d-449c38814ae3

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version Humble

**Comment by thedevmanek** [comment]
Note. The controller does not work at all when stamped:true

**Comment by christophfroehlich** [comment]
@thedevmanek @imedpsd have you solved the issue, does this still happen?

**Comment by imedpsd** [comment]
Hello, Sorry I moved on I don't have it now to reproduce it but the last time I used it it wasn't working.

**Comment by christophfroehlich** [comment]
I can't reproduce this

- `ros2 launch gz_ros2_control_demos mecanum_drive_example.launch.py`
- publishing and stopping later (stamped, but empty header) 
```
ros2 topic pub --rate 10 /cmd_vel geometry_msgs/msg/TwistStamped "
      twist:
        linear:
          x: 0.7
          y: 0.0
          z: 0.0
        angular:
          x: 0.0
          y: 0.0
          z: -1.0"
```

- robot stops
- publish again
- robot moves
