### ISSUE TITLE
cannot make JointGroupVelocityController work

### ISSUE THREAD

**Issue by muttistefano** [ros-controls/ros2_controllers#537]
Hi all, 
i'm using ros2_controllers on rolling to control a robot with the velocity interface.

My controllers config looks like this : 

```
forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

forward_velocity_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      # interface_name: velocity
```

when I show the hardware interfaces with the CLI command, it shows:
```
command interfaces
	elbow_joint/position [available] [unclaimed]
	elbow_joint/velocity [available] [claimed]
	shoulder_lift_joint/position [available] [unclaimed]
	shoulder_lift_joint/velocity [available] [claimed]
	shoulder_pan_joint/position [available] [unclaimed]
	shoulder_pan_joint/velocity [available] [claimed]
	wrist_1_joint/position [available] [unclaimed]
	wrist_1_joint/velocity [available] [claimed]
	wrist_2_joint/position [available] [unclaimed]
	wrist_2_joint/velocity [available] [claimed]
	wrist_3_joint/position [available] [unclaimed]
	wrist_3_joint/velocity [available] [claimed]
```

The controller picks up the commands published on "/forward_velocity_controller/commands", I checked by printing them in the forwardcommandcontroller Update call.
After the controller receives the commands, they are not passed down to the hardware interface.
I also tested the hardware interface extensively, and I never receive commands from the controller.
Am I doing something wrong?
