### ISSUE TITLE
[JTC] Trajectory replacement does not interpolate from active trajectory

### ISSUE THREAD

**Issue by christophfroehlich** [ros-controls/ros2_controllers#574]
**Describe the bug**
While copying documentation from [ROS 1 Wiki](http://wiki.ros.org/joint_trajectory_controller/UnderstandingTrajectoryReplacement) we realized that the trajectory replacement [does not work as expected](https://github.com/ros-controls/ros2_controllers/pull/566#discussion_r1161112731). 

**To Reproduce**
1. Checkout the jtc_tests branch from my [gazebo_ros2_control](https://github.com/christophfroehlich/gazebo_ros2_control/tree/jtc_tests) fork
2. Run [this launch file](https://github.com/christophfroehlich/gazebo_ros2_control/blob/jtc_tests/gazebo_ros2_control_demos/launch/cart_example_velocity_jtc.launch.py)
`ros2 launch gazebo_ros2_control_demos cart_example_velocity_jtc.launch.py `
3. Run [this action client](https://github.com/christophfroehlich/gazebo_ros2_control/blob/jtc_tests/gazebo_ros2_control_demos/examples/example_position_with_velocity_nonzero.cpp)
`ros2 run gazebo_ros2_control_demos example_position_with_velocity_nonzero`
4. Run it again before the old goal was reached.

Used JTC configuration:
```
joint_trajectory_controller:
  ros__parameters:
    joints:
      - slider_to_cart
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_stop: true
    gains.slider_to_cart.ff_velocity_scale: 1.0
```

Action goal:
* position + velocity points are sent -> cubic spline.
* `traj start` is left zero, which means "start now" acc to [ROS 1 Wiki](http://wiki.ros.org/joint_trajectory_controller#Trajectory_replacement) and as far as I understand the [code here](https://github.com/ros-controls/ros2_controllers/blob/master/joint_trajectory_controller/src/trajectory.cpp#L80).

**Expected behavior**
The trajectory should be interpolated from the current state (or current desired values) to the new one, as described in the [ROS 1 Wiki](http://wiki.ros.org/joint_trajectory_controller/UnderstandingTrajectoryReplacement)

**Screenshots**
At 9s a new action goal was sent and immediately overridden by the new one:
![image](https://user-images.githubusercontent.com/3367244/232339735-e5da203c-470c-49b9-bfda-336d6541b3c6.png)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: master branches of ros-controls repos
