### ISSUE TITLE
JointTrajectoryController jiggling

### ISSUE THREAD

**Issue by andrey-pr** [ros-controls/ros2_controllers#584]
Hallo. I'm trying to launch moveit servo with joint_trajectory_controller, and here is the plot of values that robot driver got on one joint:
![изображение](https://user-images.githubusercontent.com/22261051/234683810-9458afb2-6593-458b-8f31-125bf5e573e1.png)
As we can see, it returns back every published message in `/right_arm_controller/joint_trajectory` topic.
Here is the record from topic:
```
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: leg
joint_names:
- torso_right_shoulder_top_joint
- right_shoulder_top_right_shoulder_bottom_joint
- right_shoulder_bottom_right_forearm_joint
- right_forearm_right_forearm_bottom_joint
- right_forearm_bottom_right_wrist_joint
- right_wrist_right_gripper_base_joint
points:
- positions:
  - 0.30864940821268205
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  velocities: []
  accelerations: []
  effort: []
  time_from_start:
    sec: 0
    nanosec: 150000000
---
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: leg
joint_names:
- torso_right_shoulder_top_joint
- right_shoulder_top_right_shoulder_bottom_joint
- right_shoulder_bottom_right_forearm_joint
- right_forearm_right_forearm_bottom_joint
- right_forearm_bottom_right_wrist_joint
- right_wrist_right_gripper_base_joint
points:
- positions:
  - 0.3194334011114212
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  velocities: []
  accelerations: []
  effort: []
  time_from_start:
    sec: 0
    nanosec: 150000000
---
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: leg
joint_names:
- torso_right_shoulder_top_joint
- right_shoulder_top_right_shoulder_bottom_joint
- right_shoulder_bottom_right_forearm_joint
- right_forearm_right_forearm_bottom_joint
- right_forearm_bottom_right_wrist_joint
- right_wrist_right_gripper_base_joint
points:
- positions:
  - 0.3302295794885404
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  velocities: []
  accelerations: []
  effort: []
  time_from_start:
    sec: 0
    nanosec: 150000000
---
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: leg
joint_names:
- torso_right_shoulder_top_joint
- right_shoulder_top_right_shoulder_bottom_joint
- right_shoulder_bottom_right_forearm_joint
- right_forearm_right_forearm_bottom_joint
- right_forearm_bottom_right_wrist_joint
- right_wrist_right_gripper_base_joint
points:
- positions:
  - 0.3409496551449958
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  velocities: []
  accelerations: []
  effort: []
  time_from_start:
    sec: 0
    nanosec: 150000000
---
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: leg
joint_names:
- torso_right_shoulder_top_joint
- right_shoulder_top_right_shoulder_bottom_joint
- right_shoulder_bottom_right_forearm_joint
- right_forearm_right_forearm_bottom_joint
- right_forearm_bottom_right_wrist_joint
- right_wrist_right_gripper_base_joint
points:
- positions:
  - 0.3516545102573185
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  - 0.0
  velocities: []
  accelerations: []
  effort: []
  time_from_start:
    sec: 0
    nanosec: 150000000
```
As I debugged, with every msg in topic controller sends one command with current position of joint, but not new position. Joint in emulator little bit slowly than command, but when I set it to return every command as state, it still jiggles:
![изображение](https://user-images.githubusercontent.com/22261051/234684901-8c3d2100-a3d9-4a72-a076-e40a24fab8a5.png)

Here is the controller config:
```
right_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
    joints:
      - torso_right_shoulder_top_joint
      - right_shoulder_top_right_shoulder_bottom_joint
      - right_shoulder_bottom_right_forearm_joint
      - right_forearm_right_forearm_bottom_joint
      - right_forearm_bottom_right_wrist_joint
      - right_wrist_right_gripper_base_joint
```

**To Reproduce**
1. Install moveit
2. Launch an example with moveit servo

**Expected behavior**
It should work smoothly, without jiggling.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: Humble, ros-humble-joint-trajectory-controller/jammy,now 2.17.2-1jammy.20230327.201927 amd64

**Additional context**
As I see by listening command topic, its not a problem of Moveit Servo, its a problem of controller.
