### ISSUE TITLE
ackermann_steering_controller with gazebo classic

### ISSUE THREAD

**Issue by space192** [ros-controls/ros2_controllers#660]
Hi !
I was wondering if there is a command interfaces built in gazebo for ackermann_steering_controller, or do I need to code it myself ? Because right now with the following code
```
    <ros2_control name="GazeboSystem" type="system">
        <hardware>
            <plugin>gazebo_ros2_control/GazeboSystem</plugin>
        </hardware>
        <joint name="fleft_steering_hinge_joint">
            <command_interface name="position" />
            <state_interface name="position"/>
        </joint>
        <joint name="fright_steering_hinge_joint">
            <command_interface name="position" />
            <state_interface name="position"/>
        </joint>
        <joint name="rleft_wheel_joint">
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>
        <joint name="rright_wheel_joint">
            <command_interface name="velocity"/>
            <state_interface name="position"/>
            <state_interface name="velocity"/>
        </joint>
    </ros2_control>
    <gazebo>
        <plugin name="gazebo_ros2_control" filename="libgazebo_ros2_control.so">
            <parameters>$(find arece_compet_python)/config/controllers.yaml</parameters>
        </plugin>
    </gazebo>
```

and here is my controllers.yaml file:
```
controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    ack_man:
      type: ackermann_steering_controller/AckermannSteeringController
ack_man:
  ros__parameters:
    rear_wheels_names: ["rleft_wheel_joint", "rright_wheel_joint"]
    front_wheels_names: ["fleft_steering_hinge_joint", "fright_steering_hinge_joint"]
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: true
    use_stamped_vel: true
    wheel_separation: 1.23
    wheel_radius: 0.2525
    wheel_base: 0.2
    pivot_distance: 0.803
    max_steering_speed: 1.5707963267948966
    max_steering_angle: 0.42
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: true
    wheelbase: 1.530
    front_wheel_track: 1.23
    rear_wheel_track: 1.23
    front_wheel_radius: 0.2525
    rear_wheel_radius: 0.2525
```

I get:
![image](https://github.com/ros-controls/ros2_controllers/assets/44359684/124907c9-5f66-41c3-befd-58c4af6e436c)
