### ISSUE TITLE
[JTC] Commands new targets after trajectory excution has finished

### ISSUE THREAD

**Issue by firesurfer** [ros-controls/ros2_controllers#760]
**Describe the bug**

We run a force limited setup where we use a JTC to command a trajectory which the actual actuator might not be able to follow completely (one servo axis). With the current version (3.14.0) we ran multiple times into the issue that after the JTC has finished execution the axis started moving into the opposite direction.
With the previous version (3.13.0) this behavior does not occur. 
**To Reproduce**

Have a setup where the actual goal cannot be reached ( in our case for example by roughly 8cm).
Command that goal. 
In like 6 to 10 cases the axis will move slowly in the opposite direction of the target (where it came from) after the JTC has finished execution. 

Configuration
```
servo_position_controller:
  ros__parameters:
    joints:
      - axis_A
      - axis_B
    command_interfaces:
      - position
    state_interfaces:
      - position
     
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: true
    constraints:
      stopped_velocity_tolerance: 0.1
      goal_time: 0.0
      axis_A: { trajectory: 0.0, goal: 0.0 }
      axis_B: { trajectory: 0.0, goal: 0.0 }


```

**Expected behavior**

The axis should stay where it is after execution has finished or should have the last point of the trajectory as target

**Environment (please complete the following information):**
 - OS:  Ubuntu 22.04
 - Version ros-iron   JTC: 3.14.0

**Additional context**

Given that 3.13.0 works it has to be one of those commits. 

![image](https://github.com/ros-controls/ros2_controllers/assets/8481806/561d5f7b-89ea-4ec5-9e21-3a46c9268dc0)

Given that 3.14.0 also introduces #759 I would suggest reverting those commits related to the JTC until a solution was found.
